package com.campusplacement.model;
import jakarta.persistence.*;
import java.time.LocalDate; import java.util.UUID;
@Entity public class Job {
 @Id private String id; @Column(nullable=false) private String title; @ManyToOne private UserAccount recruiter; private String roleType,workMode,location,description,companyName,logoUrl,website; private double salaryLpa,minCgpa; private int maxBacklogs,openPositions; private LocalDate applyDeadline;
 protected Job(){} public Job(String id,String title,String companyName,String location,double salary){this.id=id;this.title=title;this.companyName=companyName;this.location=location;this.salaryLpa=salary;this.roleType="Full Time";this.workMode="Hybrid";this.description="A career opportunity through the campus placement portal.";this.applyDeadline=LocalDate.now().plusMonths(1);}
 public void assignRecruiter(UserAccount recruiter){this.recruiter=recruiter;} public UserAccount getRecruiter(){return recruiter;}
 public void update(String title,String roleType,String workMode,String location,double salaryLpa,String description,double minCgpa,int maxBacklogs,int openPositions,LocalDate applyDeadline,String companyName,String logoUrl,String website){this.title=title;this.roleType=roleType;this.workMode=workMode;this.location=location;this.salaryLpa=salaryLpa;this.description=description;this.minCgpa=minCgpa;this.maxBacklogs=maxBacklogs;this.openPositions=openPositions;this.applyDeadline=applyDeadline;this.companyName=companyName;this.logoUrl=logoUrl;this.website=website;}
 public String getId(){return id;} public String getTitle(){return title;} public String getRoleType(){return roleType;} public String getWorkMode(){return workMode;} public String getLocation(){return location;} public String getDescription(){return description;} public String getCompanyName(){return companyName;} public String getLogoUrl(){return logoUrl;} public String getWebsite(){return website;} public double getSalaryLpa(){return salaryLpa;} public double getMinCgpa(){return minCgpa;} public int getMaxBacklogs(){return maxBacklogs;} public int getOpenPositions(){return openPositions;} public LocalDate getApplyDeadline(){return applyDeadline;}
}
