package com.campusplacement.api;
import com.campusplacement.model.*; import com.campusplacement.repository.*; import jakarta.servlet.http.HttpSession; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import org.springframework.http.HttpStatus; import org.springframework.web.bind.annotation.*; import java.util.*; import java.util.stream.*;
@RestController @RequestMapping("/api") public class PlacementController {
 private final UserRepository users; private final ProfileRepository profiles; private final JobRepository jobs; private final ApplicationRepository applications;
 PlacementController(UserRepository users,ProfileRepository profiles,JobRepository jobs,ApplicationRepository applications){this.users=users;this.profiles=profiles;this.jobs=jobs;this.applications=applications;}
 private UserAccount current(HttpSession s){Object id=s.getAttribute("userId");if(id==null)throw new SecurityException("Sign in is required");return users.findById(UUID.fromString(id.toString())).orElseThrow(()->new SecurityException("Session is no longer valid"));}
 record ProfileInput(String phone,String usn,String branch,@Min(1) @Max(12) Integer semester,@DecimalMin("0") @DecimalMax("10") Double cgpa,@Min(0) @Max(20) Integer backlogs,String skills,String linkedin,String github,String portfolio,String resumeUrl,String bio){}
 record ProfileView(String fullName,String phone,String usn,String branch,Integer semester,Double cgpa,Integer backlogs,List<String> skills,String linkedin,String github,String portfolio,String resumeUrl,String bio){}
 record JobView(String id,String title,String roleType,String workMode,String location,double salaryLpa,String description,double minCgpa,int maxBacklogs,int openPositions,java.time.LocalDate applyDeadline,String companyName,String logoUrl,String website){}
 record ApplicationView(UUID id,String status,java.time.Instant appliedAt,JobView job){}
 private ProfileView profileView(UserAccount u,StudentProfile p){return new ProfileView(u.getFullName(),p.getPhone(),p.getUsn(),p.getBranch(),p.getSemester(),p.getCgpa(),p.getBacklogs(),p.getSkills().isBlank()?List.of():Arrays.stream(p.getSkills().split(",")).filter(x->!x.isBlank()).toList(),p.getLinkedin(),p.getGithub(),p.getPortfolio(),p.getResumeUrl(),p.getBio());}
 private JobView jobView(Job j){return new JobView(j.getId(),j.getTitle(),j.getRoleType(),j.getWorkMode(),j.getLocation(),j.getSalaryLpa(),j.getDescription(),j.getMinCgpa(),j.getMaxBacklogs(),j.getOpenPositions(),j.getApplyDeadline(),j.getCompanyName(),j.getLogoUrl(),j.getWebsite());}
 @GetMapping("/jobs") List<JobView> jobs(){return jobs.findAll().stream().map(this::jobView).toList();}
 @GetMapping("/profile") ProfileView profile(HttpSession s){UserAccount u=current(s);StudentProfile p=profiles.findById(u.getId()).orElseThrow(()->new IllegalArgumentException("Only student accounts have a profile"));return profileView(u,p);}
 @PutMapping("/profile") ProfileView updateProfile(@RequestBody @Valid ProfileInput input,HttpSession s){UserAccount u=current(s);StudentProfile p=profiles.findById(u.getId()).orElseThrow(()->new IllegalArgumentException("Only student accounts have a profile"));p.update(n(input.phone()),n(input.usn()),n(input.branch()),input.semester(),input.cgpa(),input.backlogs(),n(input.skills()),n(input.linkedin()),n(input.github()),n(input.portfolio()),n(input.resumeUrl()),n(input.bio()));return profileView(u,profiles.save(p));}
 private String n(String v){return v==null?"":v.trim();}
 @GetMapping("/applications") List<ApplicationView> applications(HttpSession s){UserAccount u=current(s);return applications.findByStudentIdOrderByAppliedAtDesc(u.getId()).stream().map(a->new ApplicationView(a.getId(),a.getStatus(),a.getAppliedAt(),jobView(a.getJob()))).toList();}
 @PostMapping("/applications/{jobId}") @ResponseStatus(HttpStatus.CREATED) ApplicationView apply(@PathVariable String jobId,HttpSession s){UserAccount u=current(s);if(!"student".equals(u.getRole()))throw new SecurityException("Only student accounts can apply to jobs");if(applications.existsByStudentIdAndJobId(u.getId(),jobId))throw new IllegalArgumentException("You have already applied for this job");Job j=jobs.findById(jobId).orElseThrow(()->new IllegalArgumentException("Job not found"));Application a=applications.save(new Application(u,j));return new ApplicationView(a.getId(),a.getStatus(),a.getAppliedAt(),jobView(j));}
 @DeleteMapping("/applications/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) void withdraw(@PathVariable UUID id,HttpSession s){UserAccount u=current(s);Application a=applications.findByIdAndStudentId(id,u.getId()).orElseThrow(()->new IllegalArgumentException("Application not found"));applications.delete(a);}
}
