package com.campusplacement.api;
import com.campusplacement.model.*; import com.campusplacement.repository.*; import jakarta.servlet.http.HttpSession; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import org.springframework.http.HttpStatus; import org.springframework.web.bind.annotation.*; import java.util.*; import java.util.stream.*;
@RestController @RequestMapping("/api") public class PlacementController {
 private final UserRepository users; private final ProfileRepository profiles; private final JobRepository jobs; private final ApplicationRepository applications;
 PlacementController(UserRepository users,ProfileRepository profiles,JobRepository jobs,ApplicationRepository applications){this.users=users;this.profiles=profiles;this.jobs=jobs;this.applications=applications;}
 private UserAccount current(HttpSession s){Object id=s.getAttribute("userId");if(id==null)throw new SecurityException("Sign in is required");return users.findById(UUID.fromString(id.toString())).orElseThrow(()->new SecurityException("Session is no longer valid"));}
 private UserAccount recruiter(HttpSession s){UserAccount user=current(s);if(!"recruiter".equals(user.getRole()))throw new SecurityException("Only recruiter accounts can manage jobs");return user;}
 record ProfileInput(String phone,String usn,String branch,@Min(1) @Max(12) Integer semester,@DecimalMin("0") @DecimalMax("10") Double cgpa,@Min(0) @Max(20) Integer backlogs,String skills,String linkedin,String github,String portfolio,String resumeUrl,String bio){}
 record ProfileView(String fullName,String phone,String usn,String branch,Integer semester,Double cgpa,Integer backlogs,List<String> skills,String linkedin,String github,String portfolio,String resumeUrl,String bio){}
 record JobView(String id,String title,String roleType,String workMode,String location,double salaryLpa,String description,double minCgpa,int maxBacklogs,int openPositions,java.time.LocalDate applyDeadline,String companyName,String logoUrl,String website){}
 record JobInput(@NotBlank @Size(max=100) String id,@NotBlank @Size(max=120) String title,@NotBlank @Size(max=80) String roleType,@NotBlank @Size(max=40) String workMode,@NotBlank @Size(max=100) String location,@DecimalMin("0") double salaryLpa,@NotBlank @Size(max=3000) String description,@DecimalMin("0") @DecimalMax("10") double minCgpa,@Min(0) @Max(50) int maxBacklogs,@Min(1) int openPositions,@NotNull java.time.LocalDate applyDeadline,@NotBlank @Size(max=120) String companyName,String logoUrl,String website){}
 record ApplicationView(UUID id,String status,java.time.Instant appliedAt,JobView job){}
 record RecruiterApplicationView(UUID id,String status,java.time.Instant appliedAt,String studentName,String studentEmail,String usn,String branch,Double cgpa,JobView job){}
 record StatusInput(@Pattern(regexp="applied|shortlisted|rejected|offered") String status){}
 private ProfileView profileView(UserAccount u,StudentProfile p){return new ProfileView(u.getFullName(),p.getPhone(),p.getUsn(),p.getBranch(),p.getSemester(),p.getCgpa(),p.getBacklogs(),p.getSkills().isBlank()?List.of():Arrays.stream(p.getSkills().split(",")).filter(x->!x.isBlank()).toList(),p.getLinkedin(),p.getGithub(),p.getPortfolio(),p.getResumeUrl(),p.getBio());}
 private JobView jobView(Job j){return new JobView(j.getId(),j.getTitle(),j.getRoleType(),j.getWorkMode(),j.getLocation(),j.getSalaryLpa(),j.getDescription(),j.getMinCgpa(),j.getMaxBacklogs(),j.getOpenPositions(),j.getApplyDeadline(),j.getCompanyName(),j.getLogoUrl(),j.getWebsite());}
 @GetMapping("/jobs") List<JobView> jobs(){return jobs.findAll().stream().map(this::jobView).toList();}
 @PostMapping("/jobs") @ResponseStatus(HttpStatus.CREATED) JobView createJob(@RequestBody @Valid JobInput input,HttpSession s){UserAccount owner=recruiter(s);if(jobs.existsById(input.id()))throw new IllegalArgumentException("A job with that ID already exists");Job job=new Job(input.id(),input.title(),input.companyName(),input.location(),input.salaryLpa());job.assignRecruiter(owner);apply(job,input);return jobView(jobs.save(job));}
 @PutMapping("/jobs/{id}") JobView updateJob(@PathVariable String id,@RequestBody @Valid JobInput input,HttpSession s){UserAccount owner=recruiter(s);if(!id.equals(input.id()))throw new IllegalArgumentException("The path ID and payload ID must match");Job job=jobs.findById(id).orElseThrow(()->new IllegalArgumentException("Job not found"));if(job.getRecruiter()!=null&&!job.getRecruiter().getId().equals(owner.getId()))throw new SecurityException("You can only edit your own jobs");apply(job,input);return jobView(jobs.save(job));}
 @DeleteMapping("/jobs/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) void deleteJob(@PathVariable String id,HttpSession s){UserAccount owner=recruiter(s);Job job=jobs.findById(id).orElseThrow(()->new IllegalArgumentException("Job not found"));if(job.getRecruiter()!=null&&!job.getRecruiter().getId().equals(owner.getId()))throw new SecurityException("You can only delete your own jobs");jobs.delete(job);}
 @GetMapping("/profile") ProfileView profile(HttpSession s){UserAccount u=current(s);StudentProfile p=profiles.findById(u.getId()).orElseThrow(()->new IllegalArgumentException("Only student accounts have a profile"));return profileView(u,p);}
 @PutMapping("/profile") ProfileView updateProfile(@RequestBody @Valid ProfileInput input,HttpSession s){UserAccount u=current(s);StudentProfile p=profiles.findById(u.getId()).orElseThrow(()->new IllegalArgumentException("Only student accounts have a profile"));p.update(n(input.phone()),n(input.usn()),n(input.branch()),input.semester(),input.cgpa(),input.backlogs(),n(input.skills()),n(input.linkedin()),n(input.github()),n(input.portfolio()),n(input.resumeUrl()),n(input.bio()));return profileView(u,profiles.save(p));}
 private String n(String v){return v==null?"":v.trim();}
 private void apply(Job job,JobInput i){job.update(i.title(),i.roleType(),i.workMode(),i.location(),i.salaryLpa(),i.description(),i.minCgpa(),i.maxBacklogs(),i.openPositions(),i.applyDeadline(),i.companyName(),n(i.logoUrl()),n(i.website()));}
 @GetMapping("/applications") List<ApplicationView> applications(HttpSession s){UserAccount u=current(s);return applications.findByStudentIdOrderByAppliedAtDesc(u.getId()).stream().map(a->new ApplicationView(a.getId(),a.getStatus(),a.getAppliedAt(),jobView(a.getJob()))).toList();}
 @GetMapping("/recruiter/applications") List<RecruiterApplicationView> recruiterApplications(HttpSession s){UserAccount owner=recruiter(s);return applications.findByJobRecruiterIdOrderByAppliedAtDesc(owner.getId()).stream().map(a->{StudentProfile p=profiles.findById(a.getStudent().getId()).orElse(null);return new RecruiterApplicationView(a.getId(),a.getStatus(),a.getAppliedAt(),a.getStudent().getFullName(),a.getStudent().getEmail(),p==null?"":p.getUsn(),p==null?"":p.getBranch(),p==null?null:p.getCgpa(),jobView(a.getJob()));}).toList();}
 @PatchMapping("/recruiter/applications/{id}") RecruiterApplicationView updateApplicationStatus(@PathVariable UUID id,@RequestBody @Valid StatusInput input,HttpSession s){UserAccount owner=recruiter(s);Application a=applications.findByIdAndJobRecruiterId(id,owner.getId()).orElseThrow(()->new IllegalArgumentException("Application not found"));a.setStatus(input.status());applications.save(a);StudentProfile p=profiles.findById(a.getStudent().getId()).orElse(null);return new RecruiterApplicationView(a.getId(),a.getStatus(),a.getAppliedAt(),a.getStudent().getFullName(),a.getStudent().getEmail(),p==null?"":p.getUsn(),p==null?"":p.getBranch(),p==null?null:p.getCgpa(),jobView(a.getJob()));}
 @PostMapping("/applications/{jobId}") @ResponseStatus(HttpStatus.CREATED) ApplicationView apply(@PathVariable String jobId,HttpSession s){UserAccount u=current(s);if(!"student".equals(u.getRole()))throw new SecurityException("Only student accounts can apply to jobs");if(applications.existsByStudentIdAndJobId(u.getId(),jobId))throw new IllegalArgumentException("You have already applied for this job");Job j=jobs.findById(jobId).orElseThrow(()->new IllegalArgumentException("Job not found"));Application a=applications.save(new Application(u,j));return new ApplicationView(a.getId(),a.getStatus(),a.getAppliedAt(),jobView(j));}
 @DeleteMapping("/applications/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) void withdraw(@PathVariable UUID id,HttpSession s){UserAccount u=current(s);Application a=applications.findByIdAndStudentId(id,u.getId()).orElseThrow(()->new IllegalArgumentException("Application not found"));applications.delete(a);}
}
